task_manager/tasks/urls.py
"""Tasks application URL Configuration."""

from django.urls import path

from task_manager.tasks.views import (
    IndexView,
    TaskCreationView,
    TaskDeleteView,
    TaskDetailView,
    TaskUpdateView,
)

app_name = 'tasks'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('create/', TaskCreationView.as_view(), name='create'),
    path('<int:pk>/', TaskDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', TaskUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', TaskDeleteView.as_view(), name='delete'),
]

task_manager/urls.py
"""Task manager project URL Configuration."""

from django.contrib import admin
from django.urls import include, path

from task_manager.users.views import UserLoginView, UserLogoutView
from task_manager.views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

tasks/urls.py
"""Tasks application URL Configuration."""

from django.urls import path

from tasks.views import (
    IndexView,
    TaskCreationView,
    TaskDeleteView,
    TaskDetailView,
    TaskUpdateView,
)

app_name = 'tasks'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('create/', TaskCreationView.as_view(), name='create'),
    path('<int:pk>/', TaskDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', TaskUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', TaskDeleteView.as_view(), name='delete'),
]

task_manager/tasks/models.py
"""Tasks application models."""

from django.db import models
from django.utils.translation import gettext_lazy as _

from task_manager.labels.models import Label
from task_manager.statuses.models import Status
from task_manager.users.models import User


class Task(models.Model):
    """Task model."""

    name = models.CharField(max_length=100, unique=True, verbose_name=_('Name'))
    description = models.TextField(blank=True, verbose_name=_('Description'))
    status = models.ForeignKey(
        Status,
        on_delete=models.PROTECT,
        verbose_name=_('Status'),
    )
    executor = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name='executor',
        verbose_name=_('Executor'),
    )
    labels = models.ManyToManyField(
        Label,
        through='Relationships',
        blank=True,
        verbose_name=_('Labels'),
    )
    created_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='created_by',
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Represent the model as a string."""
        return self.name


class Relationships(models.Model):
    """Intermediary model."""

    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    label = models.ForeignKey(Label, on_delete=models.PROTECT)

tasks/models.py
"""Tasks application models."""

from django.db import models
from django.utils.translation import gettext_lazy as _

from labels.models import Label
from statuses.models import Status
from users.models import User


class Task(models.Model):
    """Task model."""

    name = models.CharField(max_length=100, unique=True, verbose_name=_('Name'))
    description = models.TextField(blank=True, verbose_name=_('Description'))
    status = models.ForeignKey(
        Status,
        on_delete=models.PROTECT,
        verbose_name=_('Status'),
    )
    executor = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name='executor',
        verbose_name=_('Executor'),
    )
    labels = models.ManyToManyField(
        Label,
        through='Relationships',
        blank=True,
        verbose_name=_('Labels'),
    )
    created_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='created_by',
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Represent the model as a string."""
        return self.name


class Relationships(models.Model):
    """Intermediary model."""

    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    label = models.ForeignKey(Label, on_delete=models.PROTECT)

task_manager/tasks/forms.py
"""Tasks application forms."""

from django.forms import ModelForm

from task_manager.tasks.models import Task


class TaskForm(ModelForm):
    """Task form."""

    class Meta(object):
        model = Task
        fields = ('name', 'description', 'status', 'executor', 'labels')

tasks/forms.py
"""Tasks application forms."""

from django.forms import ModelForm

from tasks.models import Task


class TaskForm(ModelForm):
    """Task form."""

    class Meta(object):
        model = Task
        fields = ('name', 'description', 'status', 'executor', 'labels')

task_manager/tasks/views.py
"""Tasks application views."""

from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from django_filters.views import FilterView

from task_manager.mixins import NoPermissionMixin, UserLoginRequiredMixin
from task_manager.tasks.filters import TasktFilter
from task_manager.tasks.forms import TaskForm
from task_manager.tasks.models import Task

CREATION_SUCCESS_MESSAGE = _('Task successfully created.')
UPDATE_SUCCESS_MESSAGE = _('Task successfully changed.')
DELETE_SUCCESS_MESSAGE = _('Task successfully deleted.')

PERMISSION_DENIED_MESSAGE = _('Only the author of the task can delete it.')


class IndexView(UserLoginRequiredMixin, FilterView, ListView):
    """Tasks page view."""

    model = Task
    filterset_class = TasktFilter
    template_name = 'tasks/task_list.html'


class TaskDetailView(UserLoginRequiredMixin, DetailView):
    """Tasks detail view."""

    model = Task


class TaskCreationView(UserLoginRequiredMixin, SuccessMessageMixin, CreateView):
    """Task creation page view."""

    model = Task
    form_class = TaskForm
    template_name = 'layouts/form.html'
    success_url = reverse_lazy('tasks:index')
    success_message = CREATION_SUCCESS_MESSAGE
    extra_context = {
        'header': _('Create a task'),
        'button': _('Create'),
    }

    def form_valid(self, form):
        form.instance.created_by = self.request.user

        return super().form_valid(form)


class TaskUpdateView(UserLoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """Update Task page view."""

    model = Task
    form_class = TaskForm
    template_name = 'layouts/form.html'
    success_url = reverse_lazy('tasks:index')
    success_message = UPDATE_SUCCESS_MESSAGE
    extra_context = {
        'header': _('Changing task'),
        'button': _('Change'),
    }


class TaskDeleteView(
    UserLoginRequiredMixin,
    NoPermissionMixin,
    SuccessMessageMixin,
    DeleteView,
):
    """Delete task page view."""

    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('tasks:index')
    permission_denied_url = reverse_lazy('tasks:index')
    success_message = DELETE_SUCCESS_MESSAGE
    permission_denied_message = PERMISSION_DENIED_MESSAGE
    extra_context = {
        'header': _('Task deletion'),
        'button': _('Yes, delete'),
    }

    def test_func(self):
        task = self.get_object()

        return self.request.user == task.created_by

tasks/views.py
"""Tasks application views."""

from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from django_filters.views import FilterView

from task_manager.mixins import NoPermissionMixin, UserLoginRequiredMixin
from tasks.filters import TasktFilter
from tasks.forms import TaskForm
from tasks.models import Task
from users.views import LOGIN_REQUIRED_MESSAGE

CREATION_SUCCESS_MESSAGE = _('Task successfully created.')
UPDATE_SUCCESS_MESSAGE = _('Task successfully changed.')
DELETE_SUCCESS_MESSAGE = _('Task successfully deleted.')

PERMISSION_DENIED_MESSAGE = _('Only the author of the task can delete it.')


class IndexView(UserLoginRequiredMixin, FilterView, ListView):
    """Tasks page view."""

    model = Task
    filterset_class = TasktFilter
    template_name = 'tasks/task_list.html'
    login_url = reverse_lazy('login')
    login_required_message = LOGIN_REQUIRED_MESSAGE


class TaskDetailView(UserLoginRequiredMixin, DetailView):
    """Tasks detail view."""

    model = Task
    login_url = reverse_lazy('login')
    login_required_message = LOGIN_REQUIRED_MESSAGE


class TaskCreationView(UserLoginRequiredMixin, SuccessMessageMixin, CreateView):
    """Task creation page view."""

    model = Task
    form_class = TaskForm
    template_name = 'layouts/form.html'
    login_url = reverse_lazy('login')
    success_url = reverse_lazy('tasks:index')
    login_required_message = LOGIN_REQUIRED_MESSAGE
    success_message = CREATION_SUCCESS_MESSAGE
    extra_context = {
        'header': _('Create a task'),
        'button': _('Create'),
    }

    def form_valid(self, form):
        form.instance.created_by = self.request.user

        return super().form_valid(form)


class TaskUpdateView(UserLoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """Update Task page view."""

    model = Task
    form_class = TaskForm
    template_name = 'layouts/form.html'
    login_url = reverse_lazy('login')
    success_url = reverse_lazy('tasks:index')
    login_required_message = LOGIN_REQUIRED_MESSAGE
    success_message = UPDATE_SUCCESS_MESSAGE
    extra_context = {
        'header': _('Changing task'),
        'button': _('Change'),
    }


class TaskDeleteView(
    UserLoginRequiredMixin,
    NoPermissionMixin,
    SuccessMessageMixin,
    DeleteView,
):
    """Delete task page view."""

    model = Task
    template_name = 'delete.html'
    login_url = reverse_lazy('login')
    success_url = reverse_lazy('tasks:index')
    permission_denied_url = reverse_lazy('tasks:index')
    login_required_message = LOGIN_REQUIRED_MESSAGE
    success_message = DELETE_SUCCESS_MESSAGE
    permission_denied_message = PERMISSION_DENIED_MESSAGE
    extra_context = {
        'header': _('Task deletion'),
        'button': _('Yes, delete'),
    }

    def test_func(self):
        task = self.get_object()

        return self.request.user == task.created_by

task_manager/tasks/templates/tasks/task_detail.html
{% extends 'layouts/base.html' %}
{% load i18n %}

{% block content %}
  <h1 class="h1 my-4">{% translate "View task" %}</h1>

  <div class="card border mb-3">
    <div class="card-header bg-white shadow-sm">
      <h5 class="m-0 p-2">{{ task.name }}</h5>
    </div>
    <div class="card-body">
      {% if task.description %}
        <p class="card-text">{{ task.description }}</p>
        <hr>
      {% endif %}
      <div class="container">
        <div class="row p-1">
          <div class="col">{% translate "Author" %}</div>
          <div class="col">{{ task.created_by }}</div>
        </div>
        <div class="row p-1">
          <div class="col">{% translate "Executor" %}</div>
          <div class="col">{{ task.executor }}</div>
        </div>
        <div class="row p-1">
          <div class="col">{% translate "Status" %}</div>
          <div class="col">{{ task.status }}</div>
        </div>
        <div class="row p-1">
          <div class="col">{% translate "Creation date" %}</div>
          <div class="col">{{ task.created_at }}</div>
        </div>
        <div class="row p-1">
          <div class="col">
           {% translate "Labels" %}:
            <ul>
              {% for label in task.labels.all %}
              <li>{{ label }}</li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="card-footer bg-white">
      <div class="row p-1">
        <div class="col text-center">
          <a href="{% url 'tasks:update' task.id  %}">{% translate "Change" %}</a>
        </div>
        <div class="col text-center">
          <a class="text-danger" href="{% url 'tasks:delete' task.id  %}">{% translate "Delete" %}</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

task_manager/tasks/templates/tasks/task_list.html
{% extends 'layouts/base.html' %}
{% load bootstrap4 %}
{% load i18n %}

{% block content %}
  <h1 class="h1 my-4">{% translate "Tasks" %}</h1>

  <a href="{% url 'tasks:create' %}">{% translate "Create a task" %}</a>

  <div class="card mb-4">
    <div class="card-body">
      <form class="form-inline" method="GET">
        {% bootstrap_form filter.form field_class='mr-4' label_class='mr-2' %}
        {% buttons %}
          <button class="btn btn-primary">{% translate "Show" %}</button>
        {% endbuttons %}
      </form>
    </div>
  </div>

  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">{% translate "Name" %}</th>
          <th scope="col">{% translate "Status" %}</th>
          <th scope="col">{% translate "Author" %}</th>
          <th scope="col">{% translate "Executor" %}</th>
          <th scope="col">{% translate "Creation date" %}</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      {% for task in task_list %}
        <tr>
          <th scope="row">{{ task.id }}</th>
          <td>
            <a href="{% url 'tasks:detail' task.id  %}">{{ task.name }}</a>
          </td>
          <td>{{ task.status }}</td>
          <td>{{ task.created_by }}</td>
          <td>{% if task.executor %}{{ task.executor }}{% endif %}</td>
          <td>{{ task.created_at }}</td>
          <td>
            <a href="{% url 'tasks:update' task.id  %}">{% translate "Change" %}</a>
            <br>
            <a class="text-danger" href="{% url 'tasks:delete' task.id  %}">{% translate "Delete" %}</a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}