labels/urls.py
"""Labels application URL Configuration."""

from django.urls import path

from labels.views import IndexView, LabelCreationView, LabelDeleteView, LabelUpdateView

app_name = 'labels'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('create/', LabelCreationView.as_view(), name='create'),
    path('<int:pk>/update/', LabelUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', LabelDeleteView.as_view(), name='delete'),
]

statuses/urls.py
"""Statuses application URL Configuration."""

from django.urls import path

from statuses.views import (
    IndexView,
    StatusCreationView,
    StatusDeleteView,
    StatusUpdateView,
)

app_name = 'statuses'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('create/', StatusCreationView.as_view(), name='create'),
    path('<int:pk>/update/', StatusUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', StatusDeleteView.as_view(), name='delete'),
]

task_manager/tasks/urls.py
"""Tasks application URL Configuration."""

from django.urls import path

from task_manager.tasks.views import (
    IndexView,
    TaskCreationView,
    TaskDeleteView,
    TaskDetailView,
    TaskUpdateView,
)

app_name = 'tasks'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('create/', TaskCreationView.as_view(), name='create'),
    path('<int:pk>/', TaskDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', TaskUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', TaskDeleteView.as_view(), name='delete'),
]

task_manager/urls.py
"""Task manager project URL Configuration."""

from django.contrib import admin
from django.urls import include, path

from task_manager.users.views import UserLoginView, UserLogoutView
from task_manager.views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

task_manager/users/urls.py
"""Users application URL Configuration."""

from django.urls import path

from task_manager.users.views import (
    IndexView,
    UserCreationView,
    UserDeleteView,
    UserUpdateView,
)

app_name = 'users'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('create/', UserCreationView.as_view(), name='create'),
    path('<int:pk>/update/', UserUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', UserDeleteView.as_view(), name='delete'),
]

tasks/urls.py
"""Tasks application URL Configuration."""

from django.urls import path

from tasks.views import (
    IndexView,
    TaskCreationView,
    TaskDeleteView,
    TaskDetailView,
    TaskUpdateView,
)

app_name = 'tasks'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('create/', TaskCreationView.as_view(), name='create'),
    path('<int:pk>/', TaskDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', TaskUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', TaskDeleteView.as_view(), name='delete'),
]

task_manager/labels/models.py
"""Labels application models."""

from django.db import models
from django.utils.translation import gettext_lazy as _

MAX_LENGTH = 100


class Label(models.Model):
    """Label model."""

    name = models.CharField(max_length=MAX_LENGTH, unique=True, verbose_name=_('Name'))
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Represent the model as a string."""
        return self.name

task_manager/statuses/models.py
"""Statuses application models."""

from django.db import models
from django.utils.translation import gettext_lazy as _


class Status(models.Model):
    """Status model."""

    name = models.CharField(max_length=100, unique=True, verbose_name=_('Name'))
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Represent the model as a string."""
        return self.name

task_manager/users/models.py
"""Users application models."""

from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """Model representing a user account."""

    def __str__(self):
        """Represent the model as a string."""
        return self.get_full_name()

task_manager/labels/forms.py
"""Labels application forms."""

from django.forms import ModelForm

from task_manager.labels.models import Label


class LabelForm(ModelForm):
    """Label form."""

    class Meta(object):
        model = Label
        fields = ('name',)

task_manager/statuses/forms.py
"""Statuses application forms."""

from django.forms import ModelForm

from task_manager.statuses.models import Status


class StatusForm(ModelForm):
    """Status form."""

    class Meta(object):
        model = Status
        fields = ('name',)

task_manager/tasks/forms.py
"""Tasks application forms."""

from django.forms import ModelForm

from task_manager.tasks.models import Task


class TaskForm(ModelForm):
    """Task form."""

    class Meta(object):
        model = Task
        fields = ('name', 'description', 'status', 'executor', 'labels')

task_manager/users/forms.py
"""User application forms."""

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _

MAX_LENGTH = 150


class UserCreateForm(UserCreationForm):
    """User form."""

    first_name = forms.CharField(
        max_length=MAX_LENGTH,
        required=True,
        label=_('Name'),
    )
    last_name = forms.CharField(
        max_length=MAX_LENGTH,
        required=True,
        label=_('Surname'),
    )

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('first_name', 'last_name', 'username')

task_manager/labels/views.py
"""Labels application views."""

from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from task_manager.labels.forms import LabelForm
from task_manager.labels.models import Label
from task_manager.mixins import ProtectedErrorMixin, UserLoginRequiredMixin

CREATION_SUCCESS_MESSAGE = _('Label successfully created.')
UPDATE_SUCCESS_MESSAGE = _('Label successfully changed.')
DELETE_SUCCESS_MESSAGE = _('Label successfully deleted.')

PROTECTED_ERROR_MESSAGE = _('Unable to delete the label because it is in use.')


class IndexView(UserLoginRequiredMixin, ListView):
    """Labels page view."""

    model = Label


class LabelCreationView(
    UserLoginRequiredMixin,
    SuccessMessageMixin,
    CreateView,
):
    """Label creation page view."""

    model = Label
    form_class = LabelForm
    template_name = 'layouts/form.html'
    success_url = reverse_lazy('labels:index')
    success_message = CREATION_SUCCESS_MESSAGE
    extra_context = {
        'header': _('Create a label'),
        'button': _('Create'),
    }


class LabelUpdateView(
    UserLoginRequiredMixin,
    SuccessMessageMixin,
    UpdateView,
):
    """Update label page view."""

    model = Label
    form_class = LabelForm
    template_name = 'layouts/form.html'
    success_url = reverse_lazy('labels:index')
    success_message = UPDATE_SUCCESS_MESSAGE
    extra_context = {
        'header': _('Changing label'),
        'button': _('Change'),
    }


class LabelDeleteView(
    UserLoginRequiredMixin,
    ProtectedErrorMixin,
    SuccessMessageMixin,
    DeleteView,
):
    """Delete label page view."""

    model = Label
    template_name = 'delete.html'
    success_url = reverse_lazy('labels:index')
    protected_error_url = reverse_lazy('labels:index')
    success_message = DELETE_SUCCESS_MESSAGE
    protected_error_message = PROTECTED_ERROR_MESSAGE
    extra_context = {
        'header': _('Label deletion'),
        'button': _('Yes, delete'),
    }

task_manager/statuses/views.py
"""Statuses application views."""

from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from task_manager.mixins import ProtectedErrorMixin, UserLoginRequiredMixin
from task_manager.statuses.forms import StatusForm
from task_manager.statuses.models import Status

CREATION_SUCCESS_MESSAGE = _('Status successfully created.')
UPDATE_SUCCESS_MESSAGE = _('Status successfully changed.')
DELETE_SUCCESS_MESSAGE = _('Status successfully deleted.')

PROTECTED_ERROR_MESSAGE = _(
    'Unable to delete the status because it is in use.',
)


class IndexView(UserLoginRequiredMixin, ListView):
    """Statuses page view."""

    model = Status


class StatusCreationView(
    UserLoginRequiredMixin,
    SuccessMessageMixin,
    CreateView,
):
    """Status creation page view."""

    model = Status
    form_class = StatusForm
    template_name = 'layouts/form.html'
    success_url = reverse_lazy('statuses:index')
    success_message = CREATION_SUCCESS_MESSAGE
    extra_context = {
        'header': _('Create a status'),
        'button': _('Create'),
    }


class StatusUpdateView(
    UserLoginRequiredMixin,
    SuccessMessageMixin,
    UpdateView,
):
    """Update status page view."""

    model = Status
    form_class = StatusForm
    template_name = 'layouts/form.html'
    success_url = reverse_lazy('statuses:index')
    success_message = UPDATE_SUCCESS_MESSAGE
    extra_context = {
        'header': _('Changing status'),
        'button': _('Change'),
    }


class StatusDeleteView(
    UserLoginRequiredMixin,
    ProtectedErrorMixin,
    SuccessMessageMixin,
    DeleteView,
):
    """Delete status page view."""

    model = Status
    template_name = 'delete.html'
    success_url = reverse_lazy('statuses:index')
    protected_error_url = reverse_lazy('statuses:index')
    success_message = DELETE_SUCCESS_MESSAGE
    protected_error_message = PROTECTED_ERROR_MESSAGE
    extra_context = {
        'header': _('Status deletion'),
        'button': _('Yes, delete'),
    }

task_manager/tasks/views.py
"""Tasks application views."""

from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from django_filters.views import FilterView

from task_manager.mixins import NoPermissionMixin, UserLoginRequiredMixin
from task_manager.tasks.filters import TasktFilter
from task_manager.tasks.forms import TaskForm
from task_manager.tasks.models import Task

CREATION_SUCCESS_MESSAGE = _('Task successfully created.')
UPDATE_SUCCESS_MESSAGE = _('Task successfully changed.')
DELETE_SUCCESS_MESSAGE = _('Task successfully deleted.')

PERMISSION_DENIED_MESSAGE = _('Only the author of the task can delete it.')


class IndexView(UserLoginRequiredMixin, FilterView, ListView):
    """Tasks page view."""

    model = Task
    filterset_class = TasktFilter
    template_name = 'tasks/task_list.html'


class TaskDetailView(UserLoginRequiredMixin, DetailView):
    """Tasks detail view."""

    model = Task


class TaskCreationView(UserLoginRequiredMixin, SuccessMessageMixin, CreateView):
    """Task creation page view."""

    model = Task
    form_class = TaskForm
    template_name = 'layouts/form.html'
    success_url = reverse_lazy('tasks:index')
    success_message = CREATION_SUCCESS_MESSAGE
    extra_context = {
        'header': _('Create a task'),
        'button': _('Create'),
    }

    def form_valid(self, form):
        form.instance.created_by = self.request.user

        return super().form_valid(form)


class TaskUpdateView(UserLoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """Update Task page view."""

    model = Task
    form_class = TaskForm
    template_name = 'layouts/form.html'
    success_url = reverse_lazy('tasks:index')
    success_message = UPDATE_SUCCESS_MESSAGE
    extra_context = {
        'header': _('Changing task'),
        'button': _('Change'),
    }


class TaskDeleteView(
    UserLoginRequiredMixin,
    NoPermissionMixin,
    SuccessMessageMixin,
    DeleteView,
):
    """Delete task page view."""

    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('tasks:index')
    permission_denied_url = reverse_lazy('tasks:index')
    success_message = DELETE_SUCCESS_MESSAGE
    permission_denied_message = PERMISSION_DENIED_MESSAGE
    extra_context = {
        'header': _('Task deletion'),
        'button': _('Yes, delete'),
    }

    def test_func(self):
        task = self.get_object()

        return self.request.user == task.created_by

task_manager/users/views.py
"""Users application Views."""

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from task_manager.mixins import (
    NoPermissionMixin,
    ProtectedErrorMixin,
    UserLoginRequiredMixin,
)
from task_manager.users.forms import UserCreateForm

CREATION_SUCCESS_MESSAGE = _('User successfully registered.')
UPDATE_SUCCESS_MESSAGE = _('User successfully changed.')
DELETE_SUCCESS_MESSAGE = _('User successfully deleted.')

LOGIN_SUCCESS_MESSAGE = _('You are logged in.')
LOGOUT_SUCCESS_MESSAGE = _('You are unlogged.')

PERMISSION_DENIED_MESSAGE = _('You have no rights to change another user.')
PROTECTED_ERROR_MESSAGE = _('Unable to delete the user because it is in use.')


class IndexView(ListView):
    """Users page view."""

    model = get_user_model()


class UserCreationView(SuccessMessageMixin, CreateView):
    """User creation page view."""

    model = get_user_model()
    form_class = UserCreateForm
    template_name = 'layouts/form.html'
    success_url = reverse_lazy('login')
    success_message = CREATION_SUCCESS_MESSAGE
    extra_context = {
        'header': _('Registration'),
        'button': _('Register'),
    }


class UserUpdateView(
    UserLoginRequiredMixin,
    NoPermissionMixin,
    SuccessMessageMixin,
    UpdateView,
):
    """Update user page view."""

    model = get_user_model()
    form_class = UserCreateForm
    template_name = 'layouts/form.html'
    success_url = reverse_lazy('users:index')
    success_message = UPDATE_SUCCESS_MESSAGE
    permission_denied_url = reverse_lazy('users:index')
    permission_denied_message = PERMISSION_DENIED_MESSAGE
    extra_context = {
        'header': _('Changing the user'),
        'button': _('Change'),
    }

    def test_func(self):
        user = self.get_object()

        return self.request.user == user


class UserDeleteView(
    UserLoginRequiredMixin,
    NoPermissionMixin,
    ProtectedErrorMixin,
    SuccessMessageMixin,
    DeleteView,
):
    """Delete user page view."""

    model = get_user_model()
    template_name = 'delete.html'
    success_url = reverse_lazy('users:index')
    protected_error_url = reverse_lazy('users:index')
    success_message = DELETE_SUCCESS_MESSAGE
    permission_denied_url = reverse_lazy('users:index')
    permission_denied_message = PERMISSION_DENIED_MESSAGE
    protected_error_message = PROTECTED_ERROR_MESSAGE
    extra_context = {
        'header': _('Deleting a user'),
        'button': _('Yes, delete'),
    }

    def test_func(self):
        user = self.get_object()

        return self.request.user == user


class UserLoginView(SuccessMessageMixin, LoginView):
    """Login page view."""

    template_name = 'layouts/form.html'
    next_page = reverse_lazy('index')
    redirect_authenticated_user = True
    success_url = reverse_lazy('users:index')
    success_message = LOGIN_SUCCESS_MESSAGE
    extra_context = {
        'header': _('Login'),
        'button': _('Log in'),
    }


class UserLogoutView(LogoutView):
    """Logout page view."""

    next_page = reverse_lazy('index')
    success_message = LOGOUT_SUCCESS_MESSAGE

    def dispatch(self, request, *args, **kwargs):
        """Take in the request and returns the response."""
        messages.info(request, self.success_message)

        return super().dispatch(request, *args, **kwargs)

task_manager/views.py
"""Task manager project views."""

from django.views.generic import TemplateView


class IndexView(TemplateView):
    """Index page view."""

    template_name = 'index.html'

task_manager/templates/layouts/base.html
{% load bootstrap4 %}
{% load i18n static %}
{% get_current_language as LANGUAGE_CODE %}

{% translate "Task Manager" as title %}

<!doctype html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/webp" href="{% static 'images/favicon.webp' %}">
    <title>{{ title }}</title>
    {% bootstrap_javascript jquery=True %}
    {% bootstrap_css %}
  </head>
  <body>
    
    <header class="navbar navbar-light navbar-expand-lg sticky-top bg-white border-bottom align-items-center py-lg-3 mb-4 shadow-sm">
      {% url 'index' as index_url %}
      {% if request.path == index_url %}
        <p class="navbar-brand active mb-0 p-2">{{ title }}</p>
      {% else %}
        <a class="navbar-brand p-2" href="{{ index_url }}">{{ title }}</a>
      {% endif %}
      <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#navbar-responsive" aria-controls="navbar-responsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar-responsive">
        <nav class="navbar-nav algin-items-start mr-auto">
          {% url 'users:index' as users_url %}
          {% if request.path == users_url %}
            <p class="nav-link active mb-0 p-2">{% translate "Users" %}</p>
          {% else %}
            <a class="nav-link p-2" href="{{ users_url }}">{% translate "Users" %}</a>
          {% endif %}
          {% if user.is_authenticated %}
            {% url 'statuses:index' as statuses_url %}
            {% if request.path == statuses_url %}
              <p class="nav-link active mb-0 p-2">{% translate "Statuses" %}</p>
            {% else %}
              <a class="nav-link p-2" href="{{ statuses_url }}">{% translate "Statuses" %}</a>
            {% endif %}
            {% url 'labels:index' as labels_url %}
            {% if request.path == labels_url %}
              <p class="nav-link active mb-0 p-2">{% translate "Labels" %}</p>
            {% else %}
              <a class="nav-link p-2" href="{{ labels_url }}">{% translate "Labels" %}</a>
            {% endif %}
            {% url 'tasks:index' as tasks_url %}
            {% if request.path == tasks_url %}
              <p class="nav-link active mb-0 p-2">{% translate "Tasks" %}</p>
            {% else %}
              <a class="nav-link p-2" href="{{ tasks_url }}">{% translate "Tasks" %}</a>
            {% endif %}
          {% endif %}
        </nav>
        <nav class="navbar-nav algin-items-start">
          {% if user.is_authenticated %}
            <form method="POST" action="{% url 'logout' %}">
              {% csrf_token %}
              <button class="btn btn-link">{% translate "Logout" %}</button>
            </form>
          {% else %}
            {% url 'login' as login_url %}
            {% if request.path == login_url %}
              <p class="nav-link active mb-0 p-2">{% translate "Login" %}</p>
            {% else %}
              <a class="nav-link text-primary p-2" href="{{ login_url }}">{% translate "Login" %}</a>
            {% endif %}
            {% url 'users:create' as create_url %}
            {% if request.path == create_url %}
              <p class="nav-link active mb-0 p-2">{% translate "Registration" %}</p>
            {% else %}
              <a class="nav-link text-primary p-2" href="{{ create_url }}">{% translate "Registration" %}</a>
            {% endif %}
          {% endif %}
        </nav>
      </div>
      </header>
    
    <main class="container">
      {% bootstrap_messages %}

      {% block content %}
      {% endblock %}
    </main>

    <footer class="container pt-4 my-md-5 pt-md-5 border-top">
      <div class="row">
        <div class="col-12 col-md">
          <small class="d-block mb-3 text-muted">&copy; {% now "Y" %}</small>
        </div>
      </div>
    </footer>

  </body>
</html>

task_manager/templates/layouts/form.html
{% extends 'layouts/base.html' %}
{% load bootstrap4 %}

{% block content %}
  <h1>{{ header }}</h1>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button class="btn btn-primary">{{ button }}</button>
    {% endbuttons %}
  </form>
{% endblock %}